### ISSUE TITLE
Chef client failing on OS restart with Amazon Linux

### ISSUE THREAD

**Issue by phanikumar1210** [dev-sec/chef-os-hardening#254] opened 2019-04-24 21:54 UTC
**Describe the bug**
When running the chef client without any Amazon Linux 1 VM restart , chef-client is working good. Once there was a restart of VM, I am getting following error for all sub sequence chef-client runs

**Expected behavior**
Chef-client to run without any errors
**Actual behavior**

```
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '255'
    ---- Begin output of sysctl -w "net.ipv6.conf.all.accept_ra=0" ----
    STDOUT:
    STDERR: error: "net.ipv6.conf.all.accept_ra" is an unknown key
    ---- End output of sysctl -w "net.ipv6.conf.all.accept_ra=0" ----
    Ran sysctl -w "net.ipv6.conf.all.accept_ra=0" returned 255

```

**Example code**

```paste below

```

**OS / Environment**
Amazon Linux 1

**Chef Version**

```
14.12.3
```

**Cookbook Version**

```
4.0.0
```

**Additional context**

**Comment by artem-sidorenko** [comment] 2019-04-26 11:07
@phanikumar1210 Thanks for raising this issue! Unfortunately I can't reproduce it with test-kitchen and vagrant in this repo, I tried:
1. kitchen verify default-amazonlinux-1
2. kitchen login
3. sudo reboot
4. wait a bit
5. kitchen converge default-amazonlinux-1

Could you maybe check if you have something, what prevents loading of ipv6 kernel module?
E.g. you can try this:
```
grep -i ipv6 /etc/modprobe.d/*
```

if you get something like:
```
/etc/modprobe.d/disable-ipv6.conf:install ipv6 /bin/true
```

this would be the reason. The ipv6 module loading is prevented and its not loaded when the system starts, so the configuration namespace `net.ipv6` isn't available in the kernel

**Comment by phanikumar1210** [comment] 2019-04-26 12:57
I am getting following response for grep -i ipv6 /etc/modprobe.d/*

 /etc/modprobe.d/CIS.conf:options ipv6 disable=1

**Comment by phanikumar1210** [comment] 2019-04-26 13:29
Removing options ipv6 disable=1 option from /etc/modprobe.d/CIS.conf resolved the issue.

**Comment by artem-sidorenko** [comment] 2019-04-26 13:39
Yeah, we also handle this requirement, but [differently](https://github.com/dev-sec/chef-os-hardening/blob/9643c9233333d47071c769051a75e489b9d4a951/recipes/sysctl.rb#L53-L55). The official recommended way is not to blacklist the IPv6 module (as it leads to different problems), but to use `net.ipv6.conf.all.disable_ipv6` for that. I can't find the link anymore, but I remember this was some recommendation from RH and this option was introduced exactly to avoid the module blacklisting.

I'm closing this issue as it looks like the problem is resolved and not related to chef-os-hardening.

**Closed by artem-sidorenko** 2019-04-26 13:39 UTC
