### ISSUE TITLE
Bug: unable to use override to disable module

### ISSUE THREAD

**Issue by ekelson-bcove** [dev-sec/chef-os-hardening#208] opened 2018-04-23 17:59 UTC
Bug: node.override['os-hardening']['components'][_package_] does not work.

How to reproduce:
node.override['os-hardening']['components']['login_defs] = false should result in no alteration of /etc/login.defs.  When attempted, login_defs.rb is still executed.

Suspected issue:
https://github.com/dev-sec/chef-os-hardening/blob/master/recipes/default.rb#L31-L33
The setting of the components state should occur in the attribute file so you can override them.

**Comment by ekelson-bcove** [comment] 2018-04-24 20:27
opened https://github.com/dev-sec/chef-os-hardening/pull/209 to fix

**Comment by artem-sidorenko** [comment] 2018-06-28 08:46
This is strange, even before #209 it should work with overrides. I'll try to reproduce it

**Comment by artem-sidorenko** [comment] 2018-06-28 08:53
@ekelson-bcove can you maybe elaborate a bit how you was setting the override value? Was it in some wrapper cookbook? In some recipe or in the attribute file?

**Comment by ekelson-bcove** [comment] 2018-06-28 13:55
I was using a wrapper cookbook.  Attributes should be defined in the attribute file anyway (proper pattern).  I was unable to successfully override the vaule..even with node.override...

example:


```# Network
node.override['os-hardening']['network']['ipv6']['enable'] = true

# ENV
node.override['os-hardening']['env']['umask'] = '027'

# AUTH

node.override['os-hardening']['auth']['pw_max_age'] = 90
node.override['os-hardening']['auth']['pw_min_age'] = 2
node.override['os-hardening']['auth']['retries'] = 10
node.override['os-hardening']['auth']['lockout_time'] = 600
node.override['os-hardening']['auth']['timeout'] = 60
node.override['os-hardening']['components']['pam'] = false
node.override['os-hardening']['auth']['maildir'] = '/var/spool/mail'

# Security
node.override['os-hardening']['security']['kernel']['enable_module_loading'] = true

include_recipe 'os-hardening'```

**Comment by artem-sidorenko** [comment] 2018-06-29 11:22
@ekelson-bcove thanks!

> Attributes should be defined in the attribute file anyway (proper pattern)

Usually yes, I totally agree. However, there are also some edge cases which force you to use recipes for this purpose. 

I can't really reproduce this behaviour, please see [this](https://github.com/artem-experiments/chef-override-test) repository for my test environment. What I see, it basically works as expected:

```
$ kitchen converge centos
...      
       Transferring files to <default-centos-7>
       Starting Chef Client, version 14.1.1
       resolving cookbooks for run list: ["test1"]
       Synchronizing Cookbooks:
         - test1 (0.0.1)
         - test2 (0.0.1)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       Processing attributes from test2 cookbook      <----------------------
       Processing attributes from test1 cookbook       <----------------------
       Processing recipes from test1 cookbook           <----------------------
       Processing recipes from test2 cookbook           <----------------------
       value at compile time - override value from attribute file of test1 cookbook      <----------------------
       Converging 1 resources
       Recipe: test2::default
         * ruby_block[display value at run time] action runvalue at runtime - override value from attribute file of test1 cookbook       <----------------------

           - execute the ruby block display value at run time

       Running handlers:
       Running handlers complete
       Chef Client finished, 1/1 resources updated in 01 seconds
       Downloading files from <default-centos-7>
       Finished converging <default-centos-7> (0m4.03s).
-----> Kitchen is finished. (0m6.08s)
```

- Evaluation order of attributes and recipes looks for me as expected
- In the end I see the override attribute I configured in the attributes of first cookbook. The same works for me when setting the override attribute directly in the recipe of test1 cookbook

I try now to add os-hardening 3.0.0 cookbook to this test setup and see how it behaves with your settings

**Comment by artem-sidorenko** [comment] 2018-06-29 11:43
@ekelson-bcove I added os-hardening to this test setup and tried it with IPv6 (please see the branch [os-hardening](https://github.com/artem-experiments/chef-override-test/tree/os-hardening), overriding works for me fine for both attributes and recipes. Can you please have a look? I guess here is something different to your setup

**Comment by ekelson-bcove** [comment] 2018-06-29 12:43
It’s very possible. I will try again.

**Comment by artem-sidorenko** [comment] 2018-07-17 09:22
@ekelson-bcove I'm closing this: I could not reproduce it, Nevertheless the PR #209 is merged. Feel free to reopen if needed

**Closed** 2018-07-17 09:22 UTC

**Comment by ekelson-bcove** [comment] 2018-07-17 11:22
Thanks!

**Comment by f0rkz** [comment] 2020-05-18 16:47
I confirm this... Overrides don't seem to work. This is super strange.
